version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      graphql-network:
        ipv4_address: 22.5.0.2

  graphql:
    image: jinternals/graphql
    ports:
      - 8080:8080
    networks:
      graphql-network:
        ipv4_address: 22.5.0.3

networks:
  graphql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 22.5.0.0/16